---
- name: Setup Server
  hosts: local
  vars:
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
  become: true
  roles:
    - { role: roles/aptitude }
    - { role: roles/postgres }
    - { role: roles/docker }
    - { role: roles/nginx }