- name: Update apt cache and install dependencies
  apt:
    update_cache: yes
    name:
      - libpq-dev
      - gcc
    state: present

- name: Install PostgreSQL and required packages
  apt:
    name: 
      - postgresql
      - postgresql-contrib
    state: present

- name: Set password for PostgreSQL user
  command: >
    sudo -u {{ postgres_user }} psql -c "ALTER USER postgres PASSWORD '{{ postgres_password }}';"

- name: Restart PostgreSQL service
  service:
    name: postgresql
    state: restarted